[package]
name = "bird"
version = "0.1.0"
authors = ["zfn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "*"
rand = "*"
